2022-04-25 17:42:27,992 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'list' object has no attribute 'replace'"), <traceback object at 0x00000227C9507180>) Internal Server Error: /news/123
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\views\generic\detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\maxim\OneDrive\Desktop\New_portal_D16\new_portal\news_portal\views.py", line 42, in get_context_data
    context['user_category'] = _(categories)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\translation\__init__.py", line 74, in gettext
    return _trans.gettext(message)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\translation\trans_real.py", line 352, in gettext
    eol_message = message.replace('\r\n', '\n').replace('\r', '\n')
AttributeError: 'list' object has no attribute 'replace'
2022-04-25 17:42:28,005 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/123 HTTP/1.1" 500 97292
2022-04-26 12:57:42,626 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 72: 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001FADC2C78C0>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 561, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 72: 'endblock'. Did you forget to register or load this tag?
2022-04-26 12:57:42,658 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 155546
2022-04-26 13:03:29,600 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('Could not parse the remainder: \' "flatpage.content"\' from \'trans "flatpage.content"\''), <traceback object at 0x000001FADC40BC80>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 130, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 127, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 106, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 479, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 477, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 692, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' "flatpage.content"' from 'trans "flatpage.content"'
2022-04-26 13:03:29,625 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 220821
2022-04-26 13:04:48,862 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001FADC75C940>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2022-04-26 13:04:48,905 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 205096
2022-04-26 14:41:53,989 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'blocktranslate' doesn't allow other block tags (seen 'if news') inside it"), <traceback object at 0x000001279C28BE40>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\templatetags\i18n.py", line 545, in do_block_translate
    raise TemplateSyntaxError("%r doesn't allow other block tags (seen %r) inside it" % (bits[0], token.contents))
django.template.exceptions.TemplateSyntaxError: 'blocktranslate' doesn't allow other block tags (seen 'if news') inside it
2022-04-26 14:41:54,013 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 179936
2022-04-26 14:59:40,521 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 12: 'tarns', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001279C2CA040>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'tarns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'tarns', expected 'endblock'. Did you forget to register or load this tag?
2022-04-26 14:59:40,546 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 208407
2022-04-26 15:04:59,459 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 12: 'tarns', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001279C145140>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 500, in parse
    compile_func = self.tags[command]
KeyError: 'tarns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 502, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 552, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'tarns', expected 'endblock'. Did you forget to register or load this tag?
2022-04-26 15:04:59,480 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 208407
2022-04-26 15:37:11,293 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid filter: 'censor'"), <traceback object at 0x000001D4A5BF8780>) Internal Server Error: /news/delete/2
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 479, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 477, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 687, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 599, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'censor'
2022-04-26 15:37:11,327 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/delete/2 HTTP/1.1" 500 178173
2022-04-26 15:41:47,237 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid filter: 'censor'"), <traceback object at 0x000001D4A6F54500>) Internal Server Error: /news/search/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 284, in do_extends
    nodelist = parser.parse()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 479, in parse
    raise self.error(token, e)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 477, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 593, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 687, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 599, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'censor'
2022-04-26 15:41:47,268 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/search/ HTTP/1.1" 500 191922
2022-04-26 16:31:01,213 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_portal_post.postTitle_en_us'), <traceback object at 0x000002505DA191C0>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_portal_post.postTitle_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 294, in render
    if match:
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 284, in __bool__
    self._fetch_all()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_portal_post.postTitle_en_us
2022-04-26 16:31:01,315 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 208921
2022-04-26 17:07:38,084 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_portal_post.pubData_en'), <traceback object at 0x000001647BD8E800>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_portal_post.pubData_en

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 294, in render
    if match:
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 284, in __bool__
    self._fetch_all()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_portal_post.pubData_en
2022-04-26 17:07:38,129 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 211185
2022-04-26 17:08:10,354 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_portal_post.postRating_en'), <traceback object at 0x00000161C645F380>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_portal_post.postRating_en

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 294, in render
    if match:
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 284, in __bool__
    self._fetch_all()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_portal_post.postRating_en
2022-04-26 17:08:10,408 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 210198
2022-04-27 09:55:40,087 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x000002243F5F0380>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2022-04-27 09:55:40,113 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 181170
2022-04-27 09:56:11,789 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'news_portal' not found. 'news_portal' is not a valid view function or pattern name."), <traceback object at 0x000002243F4B5DC0>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'news_portal' not found. 'news_portal' is not a valid view function or pattern name.
2022-04-27 09:56:11,808 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 181282
2022-04-27 09:58:08,821 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x00000227594ADC40>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2022-04-27 09:58:08,843 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 181307
2022-04-27 09:58:12,947 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x0000022759517E40>) Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2022-04-27 09:58:12,964 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET /news/ HTTP/1.1" 500 181173
2022-04-27 09:58:16,683 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x00000227592E10C0>) Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2022-04-27 09:58:16,705 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET / HTTP/1.1" 500 175218
2022-04-27 09:59:20,856 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x000001E69A588140>) Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2022-04-27 09:59:20,903 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET / HTTP/1.1" 500 175355
2022-04-27 09:59:39,270 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x000001F9E0C6E6C0>) Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 176, in render
    return self._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 168, in _render
    return self.nodelist.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 977, in render
    return SafeString(''.join([
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\base.py", line 938, in render_annotated
    return self.render(context)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\urls\resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2022-04-27 09:59:39,301 ERROR    C:\Users\maxim\PycharmProjects\django\venv\lib\site-packages\django\core\servers\basehttp.py None     "GET / HTTP/1.1" 500 175355
